### PR TITLE
removed duplicate paragraph in r.osm.de/about

### PR DESCRIPTION
**Pull request by HolgerJeromin**

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
It was a little bit hard to find this repo. Do we want to link this file on github?

**Comment by datendelphin** [comment]
How or where would you like to link to make it more discoverable?

**Comment by HolgerJeromin** [comment]
We have a list of used software. We could add a link below. Quick devTools mockup:

 
image

**Comment by datendelphin** [comment]
looks good. Maybe we could even use "Server configuration" as the heading and "The server configuration is available as chef scripts in a github repository, too. There you can also find auxiliary files like this page." as an explanation.

**Pull request merged**
